version: '3.8'

services:
  postgres:
    build:
      context: ./database/
      dockerfile: Dockerfile
    container_name: angler_DB_n
    user: postgres
    environment:
      POSTGRES_USER: miha_dev
      POSTGRES_PASSWORD: miha_dev
      POSTGRES_DB: angler_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql_prodd/data
    networks:
      - Angler_net

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - Angler_net

  backend:
    build:
      context: ./angler_backend/
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./containers:/mnt/containers
      - ./docker_host:/mnt/docker_host
      - ./frontend:/mnt/frontend
    networks:
      - Angler_net
    user: root

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - Angler_net

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./.reverse_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - Angler_net

volumes:
  postgres_data:

networks:
  Angler_net:
    external: true
