services:
  postgres:
    build:
      context: ./database/
      dockerfile: Dockerfile
    container_name: angler_DB_n
    user: postgres
    environment:
      POSTGRES_USER: miha_dev
      POSTGRES_PASSWORD: miha_dev
      POSTGRES_DB: angler_dev
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql_prodd/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
