# Generated by Django 4.2.10 on 2024-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
    ]
