# Generated by Django 5.0.2 on 2024-07-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllContainers',
            fields=[
                ('container_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('container_name', models.CharField(max_length=100)),
                ('container_group', models.CharField(default='Core', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationContainers',
            fields=[
                ('app_container_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('container_id', models.IntegerField(blank=True, null=True)),
                ('position', models.JSONField(blank=True, null=True)),
                ('arguments', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('app_date_last_modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('app_container_id', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='LinkContainers',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('origin_edge', models.CharField(max_length=10)),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('destination_edge', models.CharField(max_length=10)),
            ],
        ),
    ]
