# Generated by Django 4.2.10 on 2024-02-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='Applications',
        ),
    ]
