# Generated by Django 4.2.10 on 2024-02-10 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0002_rename_apps_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='applications',
            name='date_last_Modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
