# Generated by Django 5.0.2 on 2024-07-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0002_applicationcontainers_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationcontainers',
            name='type',
        ),
        migrations.AddField(
            model_name='allcontainers',
            name='type',
            field=models.CharField(default='ContNode', max_length=30),
        ),
    ]
