# Generated by Django 5.0.2 on 2024-07-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0003_remove_applicationcontainers_type_allcontainers_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcontainers',
            old_name='type',
            new_name='container_type',
        ),
    ]
