# Generated by Django 5.0.2 on 2024-07-27 21:56

import angler_core.overwriteStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0004_rename_type_allcontainers_container_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=angler_core.overwriteStorage.OverwriteStorage(), upload_to='documents/'),
        ),
    ]
