# Generated by Django 5.0.2 on 2024-07-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0005_applications_short_desc_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='used_containers',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
