# Generated by Django 4.2.10 on 2024-02-10 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0006_alter_applications_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='applications',
            name='date_last_Modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
