# Generated by Django 5.0.2 on 2024-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0009_applicationcontainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontainers',
            name='next_containet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationcontainers',
            name='prev_container',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
