# Generated by Django 5.0.2 on 2024-02-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0010_applicationcontainers_next_containet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationcontainers',
            old_name='next_containet',
            new_name='next_container',
        ),
    ]
