# Generated by Django 5.0.2 on 2024-02-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0011_rename_next_containet_applicationcontainers_next_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationcontainers',
            old_name='container_id',
            new_name='app_container_id',
        ),
    ]
