# Generated by Django 5.0.2 on 2024-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0013_applicationcontainers_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontainers',
            name='container_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
