# Generated by Django 5.0.2 on 2024-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0014_applicationcontainers_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcontainers',
            name='position_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationcontainers',
            name='position_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
