# Generated by Django 5.0.2 on 2024-03-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0015_applicationcontainers_position_x_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllContainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField(blank=True, null=True)),
                ('container_name', models.CharField(max_length=100)),
            ],
        ),
    ]
