# Generated by Django 5.0.2 on 2024-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0017_remove_allcontainers_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkContainers',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('origin', models.IntegerField(blank=True, null=True)),
                ('origin_edge', models.IntegerField(blank=True, null=True)),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('destination_edge', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='allcontainers',
            name='container_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
