# Generated by Django 5.0.2 on 2024-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0018_linkcontainers_alter_allcontainers_container_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkcontainers',
            name='app_id_link',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
