# Generated by Django 5.0.2 on 2024-07-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0022_applicationcontainers_arguments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='date_last_Modified',
            new_name='date_last_Modifieda',
        ),
    ]
