# Generated by Django 5.0.2 on 2024-07-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0024_rename_date_last_modifieda_applications_date_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='date_last_Modified',
            new_name='app_date_last_Modified',
        ),
    ]
