# Generated by Django 5.0.2 on 2024-07-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0025_rename_date_last_modified_applications_app_date_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkcontainers',
            old_name='app_id_link',
            new_name='app_id',
        ),
    ]
