# Generated by Django 5.0.2 on 2024-07-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0026_rename_app_id_link_linkcontainers_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
