# Generated by Django 5.0.2 on 2024-07-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0027_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='app_container_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
