# Generated by Django 5.0.2 on 2024-07-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angler_core', '0028_files_app_container_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationcontainers',
            name='next_container',
        ),
        migrations.RemoveField(
            model_name='applicationcontainers',
            name='prev_container',
        ),
    ]
